In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('Datasets/questions.csv')

In [3]:
df.shape

(404351, 6)

In [4]:
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [7]:
new_df = df.sample(30000)

In [8]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [9]:
new_df.duplicated().sum()

np.int64(0)

In [10]:
ques_df = new_df[['question1','question2']]
ques_df.head()

,question1,question2
72463,How can I self publish a book in Finland?,How can I Self Publish Book in Poland?
352136,I accidentially deleted my admin account from ...,How do I upgrade from Ubuntu 15.10 to Ubuntu 1...
388963,"How is the word ""indignantly"" used in a sentence?",How is the word 'courtier' used in a sentence?
100759,Why is the Lorentz transformation the derivati...,What is lorentz number?
388936,Can taking a whey protein shake after workouts...,Can taking whey protein after workouts and bef...

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features = 3000) # jo sabse important 3000 words hain sirf usi ka features banana hain
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(), 2)

In [14]:
temp_df1 = pd.DataFrame(q1_arr, index = ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index = ques_df.index)
temp_df = pd.concat([temp_df1, temp_df2], axis = 1) # axis=1 → join columns horizontally
temp_df.shape

(30000, 6000)

In [15]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [16]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
72463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
352136,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
388963,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100759,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
388936,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_trian, y_test = train_test_split(temp_df.iloc[:,0:-1].values, temp_df.iloc[:,-1].values, test_size = 0.2, random_state = 42)

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(x_train, y_trian)
y_pred = rf.predict(x_test)
accuracy_score(y_test, y_pred)

0.7443333333333333

In [23]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(x_train, y_trian)
y_pred = xgb.predict(x_test)
accuracy_score(y_test, y_pred)

0.7281666666666666